version: "3.9"
services:

  api_bloodyspy:
    image: paultessier/bloodyspy:${APP_VERSION}
    container_name: bloodyspy-container
    networks:
      - fastapi-testing-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    ports:
      - target: 8000
        published: 8000
        protocol: tcp
        mode: host

  test1_bloodyspy:
    image: bloodyspy:curl_test
    container_name: test-curl-container
    networks:
      - fastapi-testing-network
    depends_on:
      - api_bloodyspy
    volumes:
      - ./data:/app/data
      - ./log:/app/log
    environment:
      - API_CONTAINER_NAME=bloodyspy-container

  test2_bloodyspy:
    image: bloodyspy:py_test
    container_name: test-py-container
    networks:
      - fastapi-testing-network
    depends_on:
      - api_bloodyspy
    volumes:
      - ./data:/app/data
      - ./log:/app/log
    environment:
      - SAVE_LOG=${SAVE_LOG}
      - DEV_MODE=OFF
      - API_CONTAINER_NAME=bloodyspy-container

networks:
  fastapi-testing-network: