FROM curlimages/curl:7.84.0
WORKDIR /app
COPY . .
EXPOSE 8000
CMD ./test_api.sh

# # FROM debian:latest
# FROM ubuntu:latest
# # RUN apt-get update && apt-get install curl
# RUN apt-get update && apt install curl